version: '3.8'

services:
  image-resizer:
    build: .
    container_name: image-resize-service
    ports:
      - "3002:3002"
    volumes:
      - /home/USERNAME/images:/app/images
      - /home/USERNAME/files:/app/files
    environment:
      - NODE_ENV=production